[package]
name = "rxdelta"
version = "0.2.1"
edition = "2024"
description = "High-speed VCDIFF (RFC 3284) patch application library and CLI, compatible with xdelta3"

[workspace]
members = ["xdelta3-wrap", "xdelta3-installer"]
resolver = "2"

[profile.release]
strip = true

[lib]
name = "rxdelta"
path = "src/lib.rs"

[[bin]]
name = "xdelta"
path = "src/bin/apply.rs"

[dependencies]
memmap2 = "0.9"
xz2 = { version = "0.1.7", features = ["static"] }
clap = { version = "4", features = ["derive"] }
fast-md5 = "1.0.0"
sha2 = "0.10"
blake3 = "1.5"

[dev-dependencies]
tempfile = "3"
